### ISSUE TITLE
Image click removes all items, instead of one

### ISSUE THREAD

**Issue by vimscape** [vimscape/ToDoo#1]
After creating a new todo item, there will be a small icon on the right site, it should close/ remove the item by clicking it. It works but if you add more than 1 todo items, only the first icon works and it deletes all the other ones aswell.

Preview: 
https://to-doo-vmsc.netlify.app/

**Comment by devluki** [comment]
Hi, I can help you with this issue, but it will require major changes in your code. Could you assign it to me? By the way, second bug is related  (todoList.remove(".todoItem") - > you are removing "todoList" element not "todoItem"), so it will be fixed too :)
