### ISSUE TITLE
Done button does affect all following elements

### ISSUE THREAD

**Issue by vimscape** [vimscape/ToDoo#5]
After pressing the blue button, a todo should be moved to the done section. This works fine, but if you create multiple todos (for example 5) and you press the blue button on the third one, all following will also be moved to the done section, which shouldnt be the case.

**Comment by devluki** [comment]
Hi Alex, you can assign it to me:)

**Comment by devluki** [comment]
Hi Alex, I just noticed that guard clauses in functions del and mov don't have much sens.  Looks like I get confused last time and done mix of two solutions, sorry for that :). I have removed both of them and added little feature to the "done" btn. After clicking btn, display property is set to none.

**Comment by vimscape** [comment]
thx for helping again, and awesome good men :) :+1:
